### ISSUE TITLE
[Suggestion] Add a sort of bundled cable that could transmit multiple line of data

### ISSUE THREAD

**Issue by Silly511** [SonarSonic/Practical-Logistics#10]
i was thinking you could add somthing like <a href="http://ftbwiki.org/Bundled_Cable">redpowers bundled cable</a>, basically a cable that could transfer multiple lines of data though a single cable.

**Comment by SonarSonic** [comment]
I plan on adding cables which can have unlimited data channels. I was planning on having a menu for selecting your input in each GUI. However i'd also give an option to select multiple inputs or all inputs. So for example the Inventory Reader would be able to connect to more than one inventory and for the info reader you could look at all of your energy storage at once. Although, this will take some time to add...

**Comment by SonarSonic** [comment]
Nearly there :)
![image](https://cloud.githubusercontent.com/assets/10425594/12661598/702a8638-c612-11e5-98ef-a53fb4eba54d.png)
![image](https://cloud.githubusercontent.com/assets/10425594/12661621/876b2e4c-c612-11e5-8cef-57988aa379c2.png)

**Comment by SonarSonic** [comment]
Added in dev
