### ISSUE TITLE
[1.10.2 - 2.0.0] Screens don't update, they display the value initially selcted

### ISSUE THREAD

**Issue by erindalc** [SonarSonic/Practical-Logistics#102]
![2016-09-22_14 46 24](https://cloud.githubusercontent.com/assets/12499779/18761555/6b33ac64-80d3-11e6-9ce3-62a8b13a5a8b.png)
![2016-09-22_14 47 10](https://cloud.githubusercontent.com/assets/12499779/18761566/760f3716-80d3-11e6-80e3-fdafe74569d3.png)

When I first selected the value, it was at 26 ticks. It stays that way instead of updating.

**Comment by SonarSonic** [comment]
Fixed in dev
