### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Fortist** [SonarSonic/Practical-Logistics#14]
http://pastebin.com/FtHRisH3
I guess it's looking for Icytoo, but Im not using it.

**Comment by SonarSonic** [comment]
Thank you, I'll have to look into this. Do you still crash with 0.0.8?

**Comment by Fortist** [comment]
No, I was just using this earlier today doing some testing with 0.8, didnt happen then.
However I did add some of those mods recently, so Ill check really quick.

**Comment by SonarSonic** [comment]
updating all your mods may help, one may have an outdated IC2 API

**Comment by Fortist** [comment]
As a matter of fact all of them are completely updated.
However, I have a feeling that Mekanism has IC2 shit inside, as it's the only one I know that actively messes with IC2 power. Gonna go check it

**Comment by SonarSonic** [comment]
I don't have Mekanism in my instance, I'm not able to check it right now though. If you have any luck let me know :)

**Comment by Fortist** [comment]
It's Mekanism. Now to see if I cant locate it inside and get rid of it and still have it work.

**Comment by Fortist** [comment]
Well, there are things I really wanted from Mekanism but I realize other mods do it better and better looking too, except for the power pipes/cables/cords. Ah well, It's dropped. Fix or dont/cant fix at you leisure.

**Comment by SonarSonic** [comment]
I might do a pull request to Mekanism to get them to update the API.
But have you managed to get it working now by adding the api? Alongside Mekansim?

**Comment by SonarSonic** [comment]
posted a hot fix http://minecraft.curseforge.com/projects/practical-logistics/files
