### ISSUE TITLE
Crash when you don't have IC2 installed

### ISSUE THREAD

**Issue by Silly511** [SonarSonic/Practical-Logistics#15]
When I right-clicked on a Info Reader without IC2 installed it crashed with <a href="http://pastebin.com/6wZw2UUk">this crash</a>.

**Comment by SonarSonic** [comment]
Same as #15, Do you have mekanism installed also? I'll try find a fix anyway though if it is a big problem.

**Comment by Silly511** [comment]
Yeah, I have mekanism installed.

**Comment by SonarSonic** [comment]
Mmm, I'm pretty sure it's just API issues but i'm not sure lets ask @aidancbrady :)

**Comment by Silly511** [comment]
Its not really a problem for me since I have IC2 installed, but some people might want mekanism but not IC2.

**Comment by SonarSonic** [comment]
http://minecraft.curseforge.com/projects/practical-logistics/files could you try out the hot fix?

**Comment by Silly511** [comment]
Yup, works fine now. Closing the issue.
