### ISSUE TITLE
[Suggestion] Allow any mods energy system to be displayed using the data reader.

### ISSUE THREAD

**Issue by Silly511** [SonarSonic/Practical-Logistics#16]
I noticed that when I attach a node to a mekanism energy cube, I can only monitor mekanism Joules, or when I attach a node to a Thermal Expansion energy cell, all I can monitor is RF. What I think you should do is make it where you can monitor any mod's energy storage blocks using any mod's energy system. So you could monitor how much EU is in a mekanism energy cube, or monitor how many Joules are in a MFSU, ect., ect.

**Comment by SonarSonic** [comment]
^^my bad sorry.
Yes I will be adding an Energy Reader hopefully in a few updates. Giving you the ability to read all of the Energy for multiple blocks using Nodes, giving you max capacity, current stored, current input, current output for everything. You'll be able to change the Energy Type as you wish.

**Comment by SonarSonic** [comment]
Getting close now :) 
![image](https://cloud.githubusercontent.com/assets/10425594/13558902/7b136bd6-e404-11e5-99d4-0c820f5bab80.png)

**Comment by SonarSonic** [comment]
Getting close now :)
![image](https://cloud.githubusercontent.com/assets/10425594/13558911/91e05f7c-e404-11e5-9e37-f81cd522fe9f.png)

**Comment by SonarSonic** [comment]
for you attention :) https://github.com/SonarSonic/Practical-Logistics/wiki/API-Documentation

**Comment by Silly511** [comment]
Thanks. :smile:
