### ISSUE TITLE
Forging Hammer can't work this mod's sapphire with Project RED.

### ISSUE THREAD

**Issue by SOL3675** [SonarSonic/Practical-Logistics#2]
![2016-01-09_17 11 44](https://cloud.githubusercontent.com/assets/16431933/12215167/5bc518f2-b6f4-11e5-91da-2a9fd55723e0.png)
It works well with Project RED's sapphire, but can't work with Practical-Logistics' sapphire.
This mod's ore generate fine.
NEI also shows only Project RED one.

**Comment by SonarSonic** [comment]
This is strange. I'll make sure all types work in the next version!

**Comment by SOL3675** [comment]
I actually use ore converter mod, so I use that until you fix this, thanks.

**Comment by SonarSonic** [comment]
I'll post the fixes tonight

**Comment by SonarSonic** [comment]
Fixed in dev
