### ISSUE TITLE
[Feature Request] Add support for my new mod's energy system

### ISSUE THREAD

**Issue by Silly511** [SonarSonic/Practical-Logistics#22]
I am currently working on a mod called Enchanted Aura that adds a new energy system called Aura, so could you add support for this? You can find the energy API [here](https://github.com/Silly511/DimensionalCore/tree/master/src/main/java/net/sparklepopprograms/core/api/energy), and download my mod [here](http://minecraft.curseforge.com/projects/enchanted-aura). Currently the only way to make power is with the Magmic Aura Engine which requires fire under it to work. To fetch how much aura is stored in a block, you first check the block's tile entity is instanceof IAuraUser, then cast it to BaseEnergyStorageBlock and do getStoredAura() or getMaxStoredAura().

**Comment by SonarSonic** [comment]
Practical Logistics has a full API which should will allow you to implement this within your mod :)

**Comment by SonarSonic** [comment]
Although might be best to wait till I have updated to the latest version, but also wait until I have documented the API

**Comment by SonarSonic** [comment]
Latest update won't have support for this yet, i'm still working on the Energy Handling system, just wanted to get the update out, cause I might not have time to this weekend.

**Comment by Silly511** [comment]
I'll wait until you add documentation for the practical logistics api and do it that way.
