### ISSUE TITLE
Better error detection

### ISSUE THREAD

**Issue by leftgangster** [SonarSonic/Practical-Logistics#23]
When I add a reader, a node behind it to a jar, and then remove it and instead add an entity node, my game crashes. You should use better try-catch error detection for such actions.

**Comment by SonarSonic** [comment]
Yeah, I plan to. What is the crash?

**Comment by leftgangster** [comment]
[crash-2016-03-01_14.39.14-server.txt](https://github.com/SonarSonic/Practical-Logistics/files/152764/crash-2016-03-01_14.39.14-server.txt)

**Comment by SonarSonic** [comment]
Fixed in dev, wasn't a try-catch situation i'd accidentally used scala arrays instead of java arrays.
