### ISSUE TITLE
Entity Node causing crash: Java NoClassDef error

### ISSUE THREAD

**Issue by Zero5211** [SonarSonic/Practical-Logistics#24]
Was messing around trying to figure out how the mod works and popped an Entity Node on the Info Reader. Minecraft hung and then crashed giving [this crash-log](http://pastebin.com/drKbSm4S)
In case you cannot see well enough to determine what blocks those are, they are an Info Reader on the left, a Channelled Cable in the middle, a Data Modifier on the right, and a Channel Selector on the top. 

![Setup](http://puu.sh/nv6Qe/a99a40a35b.jpg)

**Comment by SonarSonic** [comment]
Duplicate of #23 I'll get this fix out as soon as I can
