### ISSUE TITLE
Data Receiver outputs coords instead of data being input

### ISSUE THREAD

**Issue by Zero5211** [SonarSonic/Practical-Logistics#26]
Updated to the latest version and noticed my Redstone Signallers weren't triggering. After a bit of poking around I popped a display screen on a data receiver and noticed it was displaying the coords. I set the Redstone Signaller to emit if the string was equal to the coords and it lit up.

![Oh no](http://puu.sh/nBbD1/1eb465be46.jpg)

![Oh dear](http://puu.sh/nBbFf/9735eef2d8.jpg)

**Comment by SonarSonic** [comment]
Yeah, I managed to break Data Emitters and Receivers in the last update, should be fixed in the next one. Apologies.

**Comment by SonarSonic** [comment]
fixed in dev
