### ISSUE TITLE
All variables in EnergyType are private

### ISSUE THREAD

**Issue by Silly511** [SonarSonic/Practical-Logistics#27]
I am attempting to make a custom EnergyType for my mod's energy system, but the name, storage, usage, and rfConversion variables are private. I looked in EnergyType and you seem to create a new EnergyType with this code:
```java
public static class AppliedEnergistics extends EnergyType {
		public AppliedEnergistics() {
			super.name = "Applied Energistics";
			super.storage = "AE";
			super.usage = "AE/t";
			super.rfConversion = 1/2;
		}
	}
```
But I can't do that because the variables are private. So how do I do this?

**Comment by AEnterprise** [comment]
as these are always required i sugest keeping them private but making them final and move them to the constructor

**Comment by SonarSonic** [comment]
Sorry I was being stupid, I will change this in the next update.

**Comment by SonarSonic** [comment]
Fixed in dev
