### ISSUE TITLE
Texture missing - transceiver

### ISSUE THREAD

**Issue by b0bst3r** [SonarSonic/Practical-Logistics#32]
Practical-Logistics-1.7.10-0.1.4.jar

In NEI and when holding the above texture is purple and black squares

![plbug](https://cloud.githubusercontent.com/assets/2760085/13668559/6cd6df54-e6b5-11e5-9e5f-4d3ad87eb8f3.png)

**Comment by SonarSonic** [comment]
Okay, noted I will make sure it's back in the next update.

**Comment by SonarSonic** [comment]
Fixed in dev
