### ISSUE TITLE
Info Readers loose their configuration when the mana pool changes it's mana levels

### ISSUE THREAD

**Issue by Buuz135** [SonarSonic/Practical-Logistics#33]
![](https://i.gyazo.com/bf8ca47e1ffb2d925f77d2c6faf03086.jpg)

![](https://i.gyazo.com/e51e388a3a2b84df1985ea8e56ebac17.jpg)

**Comment by SonarSonic** [comment]
Wow thanks for you comprehensive list of bugs, I will also look into this one :)

**Comment by SonarSonic** [comment]
Fixed in dev
