### ISSUE TITLE
Crash with MFR and PL

### ISSUE THREAD

**Issue by b0bst3r** [SonarSonic/Practical-Logistics#34]
Crash report  - http://pastebin.com/1ANaUdU2

Video recording the crash which was repeatable - https://youtu.be/cgI9yn-i75E

Reading the crash log you maybe thinking what's that got to do with PL, well that's why I recorded the video, the crashlog doesn't mention PL anywhere but after you watch the linked video you will quite clearly see it is.

In that world I can repeat this over and over, I don't not have any MFR items in my inventory.  It only seems to happen in that 1 spot, I can place a screen above it without crashing but not that one.  It always crashes placing a screen there.

Practical-Logistics-1.7.10-0.1.4.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar (tried with 2.8.2B1.177also)

This may be a one off spot, in a one off world which may never happen again but yeah weird.

**Comment by b0bst3r** [comment]
Ok so I built on and expanded the screen and found a 2nd spot this happens on

**Comment by SonarSonic** [comment]
Thanks, this is a very bizarre crash indeed, thanks for reporting I will look into it as soon as I can.

**Comment by SonarSonic** [comment]
I have been enable to recreate, not really sure what might be the cause to be honest :(

**Comment by AEnterprise** [comment]
it seems to be there is a "corrupted" block in the area and when you break a block in that chunk you basicly force the chunk to re-render, causing it to crash

**Comment by SonarSonic** [comment]
Oh okay thanks :)
What should I do to try and find the source?

**Comment by AEnterprise** [comment]
i don't think you can do anything about this, MFR needs to fix that out of bounds exception on there end

**Comment by b0bst3r** [comment]
Sorry Sonic, this crash happens without calc and PL, just crash happened when I added both mods, totally coincidental.  Shan't bother Skyboy with it he doesn't seem at all bothered about his crashes.

**Comment by SonarSonic** [comment]
Okay glad to have this confirmed :)
