### ISSUE TITLE
Rendering Crash [PL v0.1.3]

### ISSUE THREAD

**Issue by Pandemoneus** [SonarSonic/Practical-Logistics#38]
I found a reproducable rendering crash in the Revolution 2 pack with Practical Logistics and its holographic display. The following steps cause the client to crash:
1. Place an OpenBlocks drum filled with Chroma (from ChromatiCraft, though any liquid might work).
2. Place a Fluid Reader next to the drum with the red side facing it.
3. Place a Holographic Display on the opposite side of the Fluid Reader.
4. In the Holographic Display GUI, press the button until it says "Fluids".
5. The client crashes with the following error log.

Crash log on PasteBin: http://pastebin.com/Djqs6CKB

**Comment by SonarSonic** [comment]
Fixed in dev
