### ISSUE TITLE
[Suggestion] Two things

### ISSUE THREAD

**Issue by zetosuru** [SonarSonic/Practical-Logistics#40]
So I've been using this mod around alot when it comes to using botania and computer craft, as I have a screen with the mana bar. I know someone said something before about numbers, but is there a way you could add that it measures what's in there, and gives a percentage? It could be useful for other inv related things.

**Comment by SonarSonic** [comment]
Vazkii the author of botania, hates numbers so I removed this feature in early versions, may add an option for it in config perhaps.

**Comment by AEnterprise** [comment]
maybe don't give an exact percentage but how the BC gates do it? trigers for when it's above/below 25%, 50%, 75% and full/empty?

**Comment by SonarSonic** [comment]
Added in dev
