### ISSUE TITLE
[Suggestion] Support EzStorage

### ISSUE THREAD

**Issue by ilvinc3nt** [SonarSonic/Practical-Logistics#41]
Your mod is really cool!

Please could you add support for this mod?

http://minecraft.curseforge.com/projects/ezstorage?gameCategorySlug=mc-mods&projectID=233225

thanks!

**Comment by SonarSonic** [comment]
That mod hasn't got an API, which could make doing so tricky.

**Comment by ilvinc3nt** [comment]
ok, thanks...maybe i sould contact ezstorage dev

**Comment by SonarSonic** [comment]
#76
