### ISSUE TITLE
Practical Logistic 0.1.5 dev crash

### ISSUE THREAD

**Issue by Armagedon13** [SonarSonic/Practical-Logistics#43]
http://pastebin.com/sQ8FnSk4
instant crash

**Comment by SonarSonic** [comment]
Your using a newer Forge Version, but could try backdating before I publish an update

**Comment by Armagedon13** [comment]
the new version of thermal expansion requires improved version of forge

**Comment by Armagedon13** [comment]
which it is the required forge version?

**Comment by SonarSonic** [comment]
yeah, I haven't updated yet but I will soon

**Comment by Armagedon13** [comment]
ty, i have problems to change fluid reader (gui) into tank mode, pressent crash

**Comment by SonarSonic** [comment]
Ty using Latest Forge Version instead of recommended
