### ISSUE TITLE
Eternal crash when placing node on RoC Blast Furnace.

### ISSUE THREAD

**Issue by ShadowsVengeance** [SonarSonic/Practical-Logistics#44]
Title says it all, placing a Practical Logistics node on a Rotarycraft Blast Furnace creates an eternal crash for me. (eternal crash meaning crash on world-load forever)

Full Crashlog: http://pastebin.com/XzgF666M

Currently testing some of the other Rotarycraft machines to see if the same error occurs.

Edit: Happened with the RoC grinder and i assume with all RoC machines.

**Comment by SonarSonic** [comment]
Update SonarCore
