### ISSUE TITLE
crash while placing microblock

### ISSUE THREAD

**Issue by chanzie** [SonarSonic/Practical-Logistics#45]
[crash-2016-03-27_11.54.20-client.txt](https://github.com/SonarSonic/Practical-Logistics/files/191008/crash-2016-03-27_11.54.20-client.txt)
when placing a microblock I am recieving this crash its put the server on lockdown where no one can log into it although the server is running fine.
am using 1.7.10-0.1.5 of practical logestics
most recent version of cofh mods
and forge 13.4.1614

**Comment by SonarSonic** [comment]
what Practical Logistics Block are you placing the microblock on? since the crash doesn't actually indicate Practical Logistics at all

**Comment by SonarSonic** [comment]
It's a render issue, run without fastcraft. or maybe updating that and Forge Multipart and try again

**Comment by chanzie** [comment]
confirmed forge multipart is at the most recent avaiable version so pulling fastcraft now

**Comment by SonarSonic** [comment]
I haven't been able to recreate this yet, I'm pushing a new build anyway.

**Comment by chanzie** [comment]
ok yea removing fastcraft did nothing, will try the new build as soon as its public but checked versions on everything and its all upto date so I have no idea

**Comment by chanzie** [comment]
updated the versions and thought was safe to place one and alas it still crashed
[crash-2016-03-31_09.55.03-client.txt](https://github.com/SonarSonic/Practical-Logistics/files/197903/crash-2016-03-31_09.55.03-client.txt)

will probably have to pull the mod to stop the crash before that we were experiencing a server ticking on a large monitor, granted it will go right back in because this idea is awsome and so far these two things I can work around by placing no micros, and no large screens

**Comment by SonarSonic** [comment]
yeah I didn't manage to work out the source of the problem. When you say Server Ticking, do you mean large amounts of overhead or something else?

**Comment by chanzie** [comment]
the server ticking was tracked back to a large screen, it was an entinty error that crashed the server the update probably took care of that, the microblock being placed is from ztones and im starting to think it may have something to do with that

**Comment by SonarSonic** [comment]
The Large Display Code was heavy, I fixed it just now so the operations per tick will be reduced massively. Have you tried regular covers from Forge Microblocks itself?

**Comment by chanzie** [comment]
going to try that in a test world also which version of java 8 are you using, after some googling I have seen some issues tied to microblocks and that as well so wanted to compare the versions we both were using

**Comment by SonarSonic** [comment]
I'm using Forge 10.13.4.1614 and Java Version 8 Update 60 (build 1.8.0_60-b27)

**Comment by chanzie** [comment]
ok same forge here i'm on java v8 update 77

**Comment by SonarSonic** [comment]
Okay i'll update Java and see then

**Comment by chanzie** [comment]
ok

**Comment by SonarSonic** [comment]
It's still working fine:/
![image](https://cloud.githubusercontent.com/assets/10425594/14183496/8742984c-f768-11e5-8289-ee1daff8f22e.png)

**Comment by chanzie** [comment]
ok so it has to be something with using ztones blocks after doing update rounds on the server today on all mods that needed it been dealing with conflicts, so once that is stable I will get the configs into my mc build and test normal blocks in a test world to see if its just something on my end cause it has to be something on my end at this point its just finding out what it is

**Comment by chanzie** [comment]
ok I tried placing a solid stone block to cover the front beside a logical screen and still a crash I have no clue what else to do at this point.

**Comment by SonarSonic** [comment]
It has to be a mod conflict, if it works for me but not for you. So is there anywhere I can download the pack your running? Then I could see if it's a mod conflict.

**Comment by chanzie** [comment]
send an email to wowchanze@gmail.com and I will send you the pack its private and not listed on any sites and since going through the process to make it public not to mention some mods that are in it dont allow public mod packs thats the best I can do

**Comment by SonarSonic** [comment]
okay I've managed to reproduce this now, should be able to track the problem down now

**Comment by chanzie** [comment]
okies

**Comment by SonarSonic** [comment]
https://www.dropbox.com/s/s7xyhk0u3d9t3cv/Practical-Logistics-1.7.10-0.1.7%20-%20FIXER.jar?dl=0

**Comment by SonarSonic** [comment]
I still haven't fixed the issue, still narrowing it down. however here is a download to a specially made .jar which will allow you to go on to a server with broken cables and destroy them, without crashing. This will only work if the server is also running 0.1.7

**Comment by SonarSonic** [comment]
0.1.8 is out now which fixes your issue :)
