### ISSUE TITLE
Data modifier with energy read 0.1.8 sonar core 1.1.0

### ISSUE THREAD

**Issue by crawln45** [SonarSonic/Practical-Logistics#48]
Adding a data modifier to an energy reader then displaying it on a screen has the screen display:
sonar.core.api.StoredEnergyStack@...

http://imgur.com/4sjEwvS

**Comment by AEnterprise** [comment]
looks like he's just writing an object to the screen instead of the object variable

**Comment by SonarSonic** [comment]
Opps, fixed in dev
