### ISSUE TITLE
Microblocks cause state corruption and broken channels

### ISSUE THREAD

**Issue by Baughn** [SonarSonic/Practical-Logistics#51]
Consider this setup, consisting of a Factorization mixer, a node, an inventory reader and a redstone signaller: https://brage.info/e12/2016-04-09_10.58.30.jpg

The inventory reader is set to read the number of water buckets, and the signaller to emit if there is more than 1 in the mixer.

Upon placing a microblock cover on the top-left data cable, the display shows "No Data"[1] and the signaller stops working. Removing the cover does not fix this, nor does removing and replacing all blocks. Only removing the cover and then restarting the server gets me back to a functional system.

1: https://brage.info/e12/2016-04-09_10.58.50.jpg

**Comment by SonarSonic** [comment]
Microblocks cause nothing but trouble. I'll look into this soon
