### ISSUE TITLE
Item Router Functionality?

### ISSUE THREAD

**Issue by ShadowsVengeance** [SonarSonic/Practical-Logistics#53]
Kind of tricky to submit this issue since there is no crash report or logs i can include, but is the current item router supposed to work (or not) like it is right now? I can barely get any functionality out of it at the moment, All I can do is get it to accept input and allow export (from other mod's pipes). Or I'm just completely confused at how it works at all

For example:

![image](https://cloud.githubusercontent.com/assets/8314499/14420920/bc7a9942-ff9c-11e5-9bfb-e92a12f3266c.png)
Works

![image](https://cloud.githubusercontent.com/assets/8314499/14420933/cb7e1626-ff9c-11e5-8711-fc6a26650ff8.png)
Does not work

![image](https://cloud.githubusercontent.com/assets/8314499/14420949/e5c48236-ff9c-11e5-903f-e3ed60220a8d.png)
Does not work

**Comment by SonarSonic** [comment]
Yeah it's broken at the moment, I'll post a fix soon

**Comment by ShadowsVengeance** [comment]
Thanks for the speedy response. As for maybe a suggestion would it be possible (game-wise and code-wise) for the item router to place items in a certain slot of an inventory? Kind of like how the inventory reader can display a certain slot.
