### ISSUE TITLE
Ticking block entity, smp crash

### ISSUE THREAD

**Issue by b0bst3r** [SonarSonic/Practical-Logistics#54]
We updated to 0.1.9 and this happens http://pastebin.ubuntu.com/15760407/

Can't get in render range of that block as it takes the server down.

Offending signaller
![bug1](https://cloud.githubusercontent.com/assets/2760085/14432443/1d3d25aa-0002-11e6-91bc-a71b6c80b067.png)

Signaller GUI
![bug2](https://cloud.githubusercontent.com/assets/2760085/14432453/2d2a132e-0002-11e6-9145-3945547f6bdf.png)

Attached Energy reader which I think is causing the issue
![bug3](https://cloud.githubusercontent.com/assets/2760085/14432457/3041331c-0002-11e6-80f8-8c573f021eb3.png)

**Comment by SonarSonic** [comment]
No problem, I can see this issue here, should be able to get a fix out tonight
