### ISSUE TITLE
Right clicking the 'Info Reader' causes server crash

### ISSUE THREAD

**Issue by iamomicron** [SonarSonic/Practical-Logistics#56]
http://termbin.com/krnp

Right clicking the info reader with an empty hand causes a server crash.

**Comment by SonarSonic** [comment]
your about 7 versions behind current :P

**Comment by iamomicron** [comment]
Wow, really. Many apologies. Must have downloaded the wrong version last night.

**Comment by SonarSonic** [comment]
haha no worries
