### ISSUE TITLE
[Mod Support] Can't yet read Progress of TE & IC2

### ISSUE THREAD

**Issue by Bitterholz** [SonarSonic/Practical-Logistics#57]
As per Title.

One cannot read out Progress and similar info from Thermal Expansion and Industrialcraft 2.5

Additionally, Block Name for TE machines allways shows (Basic) after the name, regardless if the Machine actually has a higher Tier or not.

**Comment by SonarSonic** [comment]
Apparently it's not possible for TE, but they can render it in GUI, so I have no idea why not... see here CoFH/Feedback#1047. IC2 don't have access to this in their API either. I could always try and get them by reflection, but this probably isn't the best idea. So for now progress isn't possible. 

As for the Machine name, I'll look into it soon.

**Comment by Bitterholz** [comment]
Well i guess its Refection or go home :/
Take a look at the Progress Providers from Logistics Pipes. They can extract Progress from TE and IC2

**Comment by SonarSonic** [comment]
#76
