### ISSUE TITLE
Excessive CPU usage in sonar.logistics.registries.EventRegistry.onServerTick()

### ISSUE THREAD

**Issue by Baughn** [SonarSonic/Practical-Logistics#61]
Hi,

Here's a Warmroast trace for you: http://i.imgur.com/Kn6nAzr.jpg

Notice that the server is spending about 20% of its CPU time inside getFirstTileEntity. I'm not sure what the cause is, although it might have to do with working on chunks that are unloaded--you need to check for that, and abort if they are--but, leaving that aside, I had a look at your code.

You're checking for the cache being empty by trying to index it, then catching the exception. Unfortunately, constructing exceptions is *really, really slow*; nearly all of that CPU is being spent constructing stack traces.

I suggest adding an explicit size check, and/or using a get variant which would return a default value. (I.e. null.)

At any rate, don't use try/catch in normal control flow.

**Comment by AEnterprise** [comment]
try/catch in normal flow? better do something about that, i have teachers who would kill someone for doing that

**Comment by SonarSonic** [comment]
lol

**Comment by Baughn** [comment]
I don't think he's kidding, although he should be. It isn't *always* a bad idea.

In this case, though, it's too expensive.

**Comment by SonarSonic** [comment]
Some guy told me I didn't use them enough. So I just threw some in places which were most likely to crash. I've never been taught so I didn't really know appropriate usage haha. I'm working on overall efficiency at the moment

**Comment by AEnterprise** [comment]
using try-catch isn't always a bad idea no, only a good idea in catching things that can go wrong so you can handle it without the whole program/mod exploding/crashing but you shouldn't rely on it to make something work as it's resource expensive and not needed as mentioned already

**Comment by Baughn** [comment]
Pretty much.

Use exceptions when you *have* to. In this case, you don't; you can just check if the array is empty beforehand.

Creating an exception is one of the most expensive things you can do.

**Comment by Baughn** [comment]
Also, you never want to catch "Exception". If you don't know what to catch, then don't; these ones would also catch, say, OutOfMemory, which is a *very bad idea*.

**Comment by SonarSonic** [comment]
That makes sense, I've removed all try and catch from Cable and Caching code. Also explains why other areas of my code seem inefficient. Also another major issue I found was caches not being deleted properly. I found that often when there were only 2 networks in the world. Almost 15 where being iterated, basically no old Caches were deleted, which often referred to those same two networks. Meaning it was checking the items/fluids/energy levels up to 15 times, which is crazy.... Already cut down Screens from 180 micro seconds to 14.

**Comment by Baughn** [comment]
You might want to look at the Guava library. That includes a lot of useful routines, including for caching, and IIRC it's bundled with Forge anyway.

(It might be excessive for your purposes, but at least take a look?)

**Comment by Baughn** [comment]
*Good work*.

I'm sure there are other optimisation opportunities, but PL no longer shows up as a major source of lag in my profiles. I suspect you don't get enough praise for things like that, therefore—take a look at this: https://goo.gl/wXW9Em

That's thanks to this fix. :-)

**Comment by SonarSonic** [comment]
Thanks! Basically just did what you guys suggested though haha
