### ISSUE TITLE
Crashing when opening Holographic Display after placing it

### ISSUE THREAD

**Issue by kaosjr** [SonarSonic/Practical-Logistics#62]
I seem to have crashed Natural Capital version 0.9.5 after attempting to open a Holographic Display after placing it.
The screen turns completely blue for 2 seconds and then closes.
Pastebin of the crash: http://pastebin.com/1d34xXjb

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by kaosjr** [comment]
quick question, what was the problem with it?

**Comment by SonarSonic** [comment]
no null check, Energy Reader outputting energy without a connected block

**Comment by kaosjr** [comment]
So i saw a fastcraft error in a log, incorrectly assumed that it was probably fastcraft, and then proceeded to crash again, this time with a dark blue screen. I see your new comment about the Energy Reader, and I'm guessing it's a new item because it's not documented in the wiki, and I don't understand why it would be null because the Energy Reader was outputting MJ information according to it.

**Comment by kaosjr** [comment]
Could you please push a release ASAP? I'm waiting on this mod to update so that I can get back on the Natural Capital server.
