### ISSUE TITLE
[Mod Support]ElectriCraft RF Storage Battery

### ISSUE THREAD

**Issue by SOL3675** [SonarSonic/Practical-Logistics#63]
It is similar problem as Draconic Evolution's RF Storage, Energy reader can't read over 2.14Billion RF.
Could you support it?
It can store up to 1.2TRF.
![2016-04-21_17 41 44](https://cloud.githubusercontent.com/assets/16431933/14703172/786f79c0-07e9-11e6-8446-66e6c96a5b72.png)

**Comment by SonarSonic** [comment]
Wow. The RF API is only designed to go to 2.14 billion, anything beyond that literally cannot be read through the API. Although I will add support at some point.

**Comment by SOL3675** [comment]
Cool to hear that!
Calculator mod side has similar API problem that display minus value of RF.(should not be post here, but this is related one :P )
![2016-04-21_20 20 00](https://cloud.githubusercontent.com/assets/16431933/14707268/b5d2873e-07fe-11e6-8369-e00b4480bfe3.png)

**Comment by SonarSonic** [comment]
Blame whoever made these stupid batteries :P

**Comment by AEnterprise** [comment]
the value going negative is probably just draconic evolution returning an overflowed int with the RF api

**Comment by SonarSonic** [comment]
#76
