### ISSUE TITLE
Energy Reader not staying selected

### ISSUE THREAD

**Issue by kaosjr** [SonarSonic/Practical-Logistics#64]
Hey,
Just noticed another bug.
When you select something on the Energy Reader and then close the menu, it will reset the selected state.
It won't show the data at all on the display.
Thanks,
kaosjr

**Comment by kaosjr** [comment]
Video of this is here: https://youtu.be/S0hPEa3_eYw

**Comment by SonarSonic** [comment]
Yeah I know the issue, I'll post a fix soon

**Comment by kaosjr** [comment]
Thanks.

**Comment by SonarSonic** [comment]
Fixed in dev
