### ISSUE TITLE
Severe Client lag Opening ae connected info reader

### ISSUE THREAD

**Issue by Bennyboy1695** [SonarSonic/Practical-Logistics#67]
As the title says, when i open a info reader thats connected to an me system it forces my client to not respond while finding all the items in my system. There's nothing being bought up in my files nor the servers files.

**Comment by SonarSonic** [comment]
could you provide screenshots of the setup your using please? can I also confirm your running the latest versions of SonarCore and Practical Logistics

**Comment by Bennyboy1695** [comment]
Yeah its on the latest version (only installed it yesterday :P) 
Info reader - http://goo.gl/mwI5dd
data emitter and node - http://goo.gl/Gqm35P
Only have about 13 me storages with items in, some arent even full on types yet

**Comment by SonarSonic** [comment]
Should be much better in the new version which will be 0.2.2. Although let me know if your still having issues.
