### ISSUE TITLE
Botania Mana Pool Info Reader client-side crash

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Practical-Logistics#68]
Steps to reproduce: connect node -> cable -> info reader (as on basic setup on the wiki) to mana pool and click "Mana: - " in I.R. (pool has mana inside).
http://codepad.org/VdwrLP4L

**Comment by MineWitherMC** [comment]
Just tested: it doesn't matter is there mana in the pool. The client crashes anyway.

**Comment by SonarSonic** [comment]
Fixed in dev
