### ISSUE TITLE
Server crash when using energy reader on multiblock EnderIO cap.bank

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Practical-Logistics#71]
After placing 2 vibrant capacitor blocks (25 MRf + 0 MRf), placing node-cable-e.reader and finally looking onto display screen connected to e.reader the following crash:
http://codepad.org/F4OvtPXM.
That world gets corrupted and I can only enter it with removal of Practical Logistics.

**Comment by SonarSonic** [comment]
Fixed in dev
