### ISSUE TITLE
Holographic display loosing data when chunkload.

### ISSUE THREAD

**Issue by Pixelmnkey** [SonarSonic/Practical-Logistics#75]
I have a setup of IE silos, a node atached to each of them with an inventory reader and an holographic display, an easy item display tbh. I have cables preventing from conecting each other with covers so each screen shows the silo they're atached. 

When I disconect from the server and reconect ( even when unloading the chunks ) the holographic screen goes to "no data", I have to break the screen and replace it.

Any fix?

Thanks!

PS: Awesome mod!

**Comment by SonarSonic** [comment]
Should be fixed in the next version. Let me know if you're still having issues.
