### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by quasarea** [SonarSonic/Practical-Logistics#77]
Bug in current (2.3) version causes item duplication:

Pattern:
* place a hopper 
* place Inventory Reader in such way that its blue end will be at hopper
* click an item into Inventory Readers slot as [stack] mode
* "ghost" item will be pulled by hopper as normal would.

![2016-06-08_18 31 53](https://cloud.githubusercontent.com/assets/10334982/15904056/6f9f49cc-2da7-11e6-9483-756cb22bde91.png)

**Comment by SonarSonic** [comment]
Fixed in dev
