### ISSUE TITLE
Crash Practical Logistics 0.0.6 And AE2 Not Present

### ISSUE THREAD

**Issue by jsaggers** [SonarSonic/Practical-Logistics#8]
Just building myself a small pack with a handful of mod's, pack works fine with Practical Logistics 0.0.5 but when I upgraded to version 0.0.6 it crashes, [pastebin here] (http://pastebin.com/SGsJbDKm)

I noticed in your change log you have added support for Logistics Pipes, so I installed that mod (and buildcraft since is is required) and I still got the crash, so I removed Logistics Pipes and I thought I would install AE2 for some reason and the game loaded just fine, using AE2 RV2-stable 10.

So with no AE2 and Practical Logistics 0.0.6 the game crashes.

**Comment by SonarSonic** [comment]
Okay thanks for reporting this i'll look into it tonight

**Comment by SonarSonic** [comment]
Fixed on the latest update.http://minecraft.curseforge.com/projects/practical-logistics/files/2276320
