### ISSUE TITLE
Allowing modpacks?

### ISSUE THREAD

**Issue by Joshwoo70** [SonarSonic/Practical-Logistics#80]
i have conflictiong statements from both Curseforge and here:
Curseforge: Mod-Packs: Feel free to use this mod in any mod-pack you wish.
Github: No re-releases of any form unless I have given expressed permission.
Could you clarify both or at least edit it? thanks.

**Comment by SonarSonic** [comment]
Mod packs are absolutely fine by me. By re-releases I mean distributing the mod and passing it off as your own work. Or creating an unofficial port to another version of Minecraft. Or attempting to post the newer versions of the mod from GitHub.
