### ISSUE TITLE
Allow Nodes to remain in position

### ISSUE THREAD

**Issue by Joshwoo70** [SonarSonic/Practical-Logistics#81]
![2016-06-26_15 56 01](https://cloud.githubusercontent.com/assets/7894419/16361116/85d4ff76-3bb6-11e6-9a2b-eb5d735ee32c.png)
![2016-06-26_15 55 42](https://cloud.githubusercontent.com/assets/7894419/16361117/85d65880-3bb6-11e6-955b-3ed257a72ff1.png)
As seen in the photo's the node pops off if the inventory(chest) is moved by an item (The dolly by JABBA is shown)
I suggest that they should remain in place even though the inventory is moved.

**Comment by SonarSonic** [comment]
Yeah I probably will change that.

**Comment by SonarSonic** [comment]
Added a while ago
