### ISSUE TITLE
World crash(singleplayer server shutdown) on accessing Inventory Reader GUI

### ISSUE THREAD

**Issue by static7s** [SonarSonic/Practical-Logistics#82]
Any time I try to access the GUI on the inventory reader, I get kicked from the world. This occurs consistently.

Full client log: http://paste.ubuntu.com/18131385/
Reduced log(Only contains log from after clicking "Play Selected World" in the menu): http://paste.ubuntu.com/18131521/

**Comment by SonarSonic** [comment]
Try updating Java looks like you're on 7.

**Comment by static7s** [comment]
That did it
