### ISSUE TITLE
Crash when attaching a display screen to a Data Receiver

### ISSUE THREAD

**Issue by Silly511** [SonarSonic/Practical-Logistics#9]
I was able to attach some cable to the Data Receiver, but when I put a display screen on the cable I got <a href="http://pastebin.com/XS7U7awT">this crash</a>. I had not named the Data Receiver.

**Comment by SonarSonic** [comment]
Fixed in previous commit. https://github.com/SonarSonic/Practical-Logistics/blob/master/src/main/java/sonar/logistics/helpers/CableHelper.java#L104 The next build will have the fix
