### ISSUE TITLE
Energy Reader question

### ISSUE THREAD

**Issue by AnarchySage** [SonarSonic/Practical-Logistics#91]
I did a node on a ult energy cube from mekanism, to reader, to cable to display(and directly reader to display), it isnt showing me the power when i click the cube in the reader.

**Comment by SonarSonic** [comment]
Did you select the energy cube inside the Energy Reader's GUI and has it gone green on the side?

**Comment by AnarchySage** [comment]
Yes

**Comment by SonarSonic** [comment]
Could maybe you post a picture of the full setup? Does the screen say 'No Data' ?

**Comment by AnarchySage** [comment]
Now i dont have it updated, its at 0.2.1 and yes it says no data, the highlighting of the cube doesnt stick.

http://imgur.com/a/qiLvw

**Comment by SonarSonic** [comment]
Wait so you're running an old version?

**Comment by SonarSonic** [comment]
Old version
