### ISSUE TITLE
mt remove recipe on forging hammer not working

### ISSUE THREAD

**Issue by wizard1399** [SonarSonic/Practical-Logistics#95]
Hello,

I am having some difficulty with removing recipes from the forging hammer.

I tried this:

mods.logistics.hammer.removeRecipe(<PracticalLogistics:StonePlate>);
mods.logistics.hammer.addRecipe(<Thaumcraft:blockCosmeticSolid:6>, <PracticalLogistics:StonePlate>);

The new recipe was added okay, but it did not take the old recipe out. The mt script loads successfully in minecraft, but does not remove the recipe. NEI still shows the old recipe after the script has been reloaded. I tried minecraft stone in the forging hammer to see if it was just a bug with NEI. The old stone -> stone plate recipe still worked as well.  

I am using Minecraft 1.7.10 and vers 0.2.4 of the mod.

**Comment by SonarSonic** [comment]
Use the ingredients not the output

**Comment by AEnterprise** [comment]
@SonarSonic that is not how mt integration is suposed to work, the ingredients of a recipe might change, breaking a script, the output however won't change

**Comment by SonarSonic** [comment]
you wrote it though...

**Comment by AEnterprise** [comment]
yes but iirc that was because your recipe system didn't allow it to be done with the recipe output and needed a partial rewrite, i'd have to check the code though as it's been a while since

**Comment by SonarSonic** [comment]
I'll probably rewrite in that case, it's not in great shape at the moment

**Comment by AEnterprise** [comment]
let's put it this way: you wrote some very unique code for recipes, i remember that, and alot of scratching my head to figure out why you did some things that way

**Comment by wizard1399** [comment]
So ... what does this mean for the pack I am developing? Should I wait for an update of practical logistics, or try to implement some form of workaround?

**Comment by AEnterprise** [comment]
for now you can just remove recipes by specifying the input instead of the output of the recipe to remove, the system is counter intuitive but it was forgotten to be fixed
