### ISSUE TITLE
[Bounty] Willing to pay for priority on issue specified inside.

### ISSUE THREAD

**Issue by iKaneki-Ken** [SonarSonic/Practical-Logistics#97]
#89 

I am willing to pay an amount of money if you put priority on that issue. I'm experiencing it as well and prevents me from having this on my server.

**Comment by SonarSonic** [comment]
I'm not really developing on 1.7.10 anymore...

**Comment by FeldrinH** [comment]
I could not reproduce the issue. Could you provide a screenshot of your setup or something?

**Comment by SonarSonic** [comment]
It's just a missing null check, the storage system probably didn't allow extract from the inventory despite the stack being present. So a null check in the AE2 Helper would fix

**Comment by iKaneki-Ken** [comment]
Gotcha, Honestly, after experiencing Modded Minecraft 1.10, I don't blame you, just so much more you can do with 1.10 compared to 1.7.10. I'll close this issue.
